22 May 2022 15:08:31,364 ERROR   Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: common
22 May 2022 15:08:31,365 ERROR   Error running template command. Exit Value = 1.
22 May 2022 15:08:31,365 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-search 
22 May 2022 15:08:31,365 ERROR   Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
22 May 2022 15:08:31,365 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
22 May 2022 15:13:41,265 ERROR   Error: YAML parse error on alfresco-dmn-service/charts/alfresco-dmn-service/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: could not find expected ':'
22 May 2022 15:13:41,265 ERROR   
22 May 2022 15:13:41,265 ERROR   Use --debug flag to render out invalid YAML
22 May 2022 15:13:41,265 ERROR   Error running template command. Exit Value = 1.
22 May 2022 15:13:41,266 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-dmn-service 
22 May 2022 15:13:41,266 ERROR   Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
22 May 2022 15:13:41,266 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
22 May 2022 15:13:42,754 ERROR   Error: YAML parse error on alfresco-dmn-service/charts/alfresco-dmn-service/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: could not find expected ':'
22 May 2022 15:13:42,754 ERROR   
22 May 2022 15:13:42,754 ERROR   Use --debug flag to render out invalid YAML
22 May 2022 15:13:42,754 ERROR   Error running template command. Exit Value = 1.
22 May 2022 15:13:42,754 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-dmn-service 
22 May 2022 15:13:42,754 ERROR   Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
22 May 2022 15:13:42,755 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
22 May 2022 15:13:42,756 ERROR   Chart alfresco-dmn-service:0.1.0 failed to print even with the refresh option
22 May 2022 15:20:35,293 ERROR   Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

22 May 2022 15:20:35,294 ERROR   Error resolving chart dependencies: Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

22 May 2022 15:20:36,887 ERROR   Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

22 May 2022 15:20:36,887 ERROR   Error resolving chart dependencies: Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

22 May 2022 15:20:36,888 ERROR   Chart process-services-infrastructure:0.1.1 failed to print even with the refresh option
