24 May 2022 16:56:48,220 ERROR   Error: found in Chart.yaml, but missing in charts/ directory: common
24 May 2022 16:56:48,220 ERROR   Error running template command. Exit Value = 1.
24 May 2022 16:56:48,221 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-search 
24 May 2022 16:56:48,221 ERROR   Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
24 May 2022 16:56:48,221 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
24 May 2022 16:58:07,217 ERROR   Chart alfresco-content-services:5.2.0 printed successfully with the refresh option. See the prior errors that occured without the refresh option to understand why refresh was needed.
24 May 2022 17:03:34,249 ERROR   Error: YAML parse error on alfresco-dmn-service/charts/alfresco-dmn-service/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: could not find expected ':'
24 May 2022 17:03:34,249 ERROR   
24 May 2022 17:03:34,249 ERROR   Use --debug flag to render out invalid YAML
24 May 2022 17:03:34,249 ERROR   Error running template command. Exit Value = 1.
24 May 2022 17:03:34,250 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-dmn-service 
24 May 2022 17:03:34,250 ERROR   Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
24 May 2022 17:03:34,250 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
24 May 2022 17:03:48,027 ERROR   Error: YAML parse error on alfresco-dmn-service/charts/alfresco-dmn-service/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: could not find expected ':'
24 May 2022 17:03:48,028 ERROR   
24 May 2022 17:03:48,028 ERROR   Use --debug flag to render out invalid YAML
24 May 2022 17:03:48,028 ERROR   Error running template command. Exit Value = 1.
24 May 2022 17:03:48,028 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-dmn-service 
24 May 2022 17:03:48,028 ERROR   Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
24 May 2022 17:03:48,028 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
24 May 2022 17:03:48,028 ERROR   Chart alfresco-dmn-service:0.1.0 failed to print even with the refresh option.
24 May 2022 17:10:38,093 ERROR   Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

24 May 2022 17:10:38,094 ERROR   Error resolving chart dependencies: Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

24 May 2022 17:10:53,394 ERROR   Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

24 May 2022 17:10:53,394 ERROR   Error resolving chart dependencies: Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

24 May 2022 17:10:53,395 ERROR   Chart process-services-infrastructure:0.1.1 failed to print even with the refresh option.
