02 Jun 2022 06:57:22,048 ERROR   Error: found in Chart.yaml, but missing in charts/ directory: common
02 Jun 2022 06:57:22,049 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 06:57:22,049 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template alfresco-search 
02 Jun 2022 06:57:22,049 ERROR   Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
02 Jun 2022 06:57:22,049 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
02 Jun 2022 07:00:02,361 ERROR   Chart alfresco-content-services:5.3.0-A178 printed successfully with the refresh option. See the prior errors that occured without the refresh option to understand why refresh was needed.
02 Jun 2022 07:07:33,364 ERROR   Error: found in Chart.yaml, but missing in charts/ directory: common
02 Jun 2022 07:07:33,365 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 07:07:33,365 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template alfresco-search 
02 Jun 2022 07:07:33,365 ERROR   Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
02 Jun 2022 07:07:33,365 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
02 Jun 2022 07:11:01,621 ERROR   Chart alfresco-content-services:5.3.0-A176 printed successfully with the refresh option. See the prior errors that occured without the refresh option to understand why refresh was needed.
02 Jun 2022 07:15:05,325 ERROR   Error: found in Chart.yaml, but missing in charts/ directory: common
02 Jun 2022 07:15:05,325 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 07:15:05,326 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template alfresco-search 
02 Jun 2022 07:15:05,326 ERROR   Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
02 Jun 2022 07:15:05,326 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
02 Jun 2022 07:19:49,493 ERROR   Chart alfresco-content-services:5.3.0-A174 printed successfully with the refresh option. See the prior errors that occured without the refresh option to understand why refresh was needed.
02 Jun 2022 07:24:08,635 ERROR   Error: YAML parse error on alfresco-dmn-service/charts/alfresco-dmn-service/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: could not find expected ':'
02 Jun 2022 07:24:08,636 ERROR   
02 Jun 2022 07:24:08,636 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 07:24:08,636 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 07:24:08,636 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template alfresco-dmn-service 
02 Jun 2022 07:24:08,636 ERROR   Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
02 Jun 2022 07:24:08,636 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
02 Jun 2022 07:24:20,184 ERROR   Error: YAML parse error on alfresco-dmn-service/charts/alfresco-dmn-service/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: could not find expected ':'
02 Jun 2022 07:24:20,185 ERROR   
02 Jun 2022 07:24:20,185 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 07:24:20,185 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 07:24:20,185 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template alfresco-dmn-service 
02 Jun 2022 07:24:20,186 ERROR   Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
02 Jun 2022 07:24:20,186 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
02 Jun 2022 07:24:20,186 ERROR   Chart alfresco-dmn-service:0.1.0 failed to print even with the refresh option.
02 Jun 2022 07:30:13,905 ERROR   Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

02 Jun 2022 07:30:13,906 ERROR   Error resolving chart dependencies: Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

02 Jun 2022 07:30:28,100 ERROR   Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

02 Jun 2022 07:30:28,101 ERROR   Error resolving chart dependencies: Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

02 Jun 2022 07:30:28,101 ERROR   Chart process-services-infrastructure:0.1.1 failed to print even with the refresh option.
