15 May 2022 11:33:16,523 ERROR   Error: found in Chart.yaml, but missing in charts/ directory: common
15 May 2022 11:33:16,523 ERROR   Error running template command. Exit Value = 1.
15 May 2022 11:33:16,523 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-search 
15 May 2022 11:33:16,523 ERROR   Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
15 May 2022 11:33:16,523 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
15 May 2022 11:39:01,804 ERROR   Error: YAML parse error on alfresco-dmn-service/charts/alfresco-dmn-service/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: could not find expected ':'
15 May 2022 11:39:01,805 ERROR   
15 May 2022 11:39:01,805 ERROR   Use --debug flag to render out invalid YAML
15 May 2022 11:39:01,806 ERROR   Error running template command. Exit Value = 1.
15 May 2022 11:39:01,806 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-dmn-service 
15 May 2022 11:39:01,806 ERROR   Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
15 May 2022 11:39:01,806 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
15 May 2022 11:39:03,284 ERROR   Error: YAML parse error on alfresco-dmn-service/charts/alfresco-dmn-service/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: could not find expected ':'
15 May 2022 11:39:03,284 ERROR   
15 May 2022 11:39:03,284 ERROR   Use --debug flag to render out invalid YAML
15 May 2022 11:39:03,284 ERROR   Error running template command. Exit Value = 1.
15 May 2022 11:39:03,284 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-dmn-service 
15 May 2022 11:39:03,285 ERROR   Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
15 May 2022 11:39:03,285 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
15 May 2022 11:39:03,287 ERROR   Chart alfresco-dmn-service:0.1.0 failed to print even with the refresh option
15 May 2022 11:46:14,097 ERROR   Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

15 May 2022 11:46:14,097 ERROR   Error resolving chart dependencies: Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

15 May 2022 11:46:15,810 ERROR   Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

15 May 2022 11:46:15,810 ERROR   Error resolving chart dependencies: Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

15 May 2022 11:46:15,810 ERROR   Chart process-services-infrastructure:0.1.1 failed to print even with the refresh option
